name: Deploy Jekyll with GitHub Pages dependencies preinstalled
on:
  pull_request:
  push:
    branches: ["master", "main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject URLs
        env:
          RESUME_URL: ${{ secrets.RESUME_URL }}
          CONTACT_URL: ${{ secrets.CONTACT_URL }}
        run: |
          touch src/_config.yml
          yq eval ".resume_url = strenv(RESUME_URL)" -i src/_config.yml
          yq eval ".contact_url = strenv(CONTACT_URL)" -i src/_config.yml
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: src
          destination: _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  # Deployment job for pull requests
  deploy_test:
    if: github.event_name == 'pull_request'
    environment:
      name: github-pages-preview
      url: ${{ steps.deployment_test.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages (Preview)
        id: deployment_test
        uses: actions/deploy-pages@v4
        with:
          preview: true # Enable preview mode
  # Deployment job on master
  deploy:
    if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
