name: Test Jekyll with GitHub Pages
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Inject URLs
        env:
          BASE_URL: ""
          RESUME_URL: ${{ secrets.RESUME_URL }}
          CONTACT_URL: ${{ secrets.CONTACT_URL }}
        run: |
          touch src/_config.yml
          yq eval ".baseurl = strenv(BASE_URL)" -i src/_config.yml
          yq eval ".resume_url = strenv(RESUME_URL)" -i src/_config.yml
          yq eval ".contact_url = strenv(CONTACT_URL)" -i src/_config.yml
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: src
          destination: _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  # Deployment job for pull requests
  # deploy_test:
  #   if: github.event_name == 'pull_request'
  #   environment:
  #     name: github-pages-preview
  #     url: ${{ steps.deployment_test.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages (Preview)
  #       id: deployment_test
  #       uses: actions/deploy-pages@v4
  #       with:
  #         preview: true # Enable preview mode
