name: Test Jekyll
on:
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject URLs
        env:
          RESUME_URL: ${{ secrets.RESUME_URL }}
          CONTACT_FORM_URL: ${{ secrets.CONTACT_FORM_URL }}
        run: |
          echo "resume_url: $RESUME_URL" >> src/_config.yml
          echo "contact_form_url: $CONTACT_FORM_URL" >> src/_config.yml
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --config ./src/_config.yml --baseurl "${{ steps.pages.outputs.base_path }}"
      - name: Inspect Output
        run: |
          echo "Current directory:"
          ls
          echo "List of files in the _site directory:"
          ls _site/
          echo "Contents of the _site/index.html file:"
          cat _site/index.html
          echo "Contents of the assets file:"
          ls _site/assets/
