name: Test Jekyll with GitHub Pages
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Inject URLs
        env:
          BASE_URL: ""
          RESUME_URL: ${{ secrets.RESUME_URL }}
          CONTACT_URL: ${{ secrets.CONTACT_URL }}
        run: |
          touch src/_config.yml
          yq eval ".baseurl = strenv(BASE_URL)" -i src/_config.yml
          yq eval ".resume_url = strenv(RESUME_URL)" -i src/_config.yml
          yq eval ".contact_url = strenv(CONTACT_URL)" -i src/_config.yml
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: src
          destination: _site
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node.js
        uses: actions/setup-node@v7
      - name: Run Test Suite
        run: |
          make test-all
