name: Test Jekyll
on:
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject URLs
        env:
          RESUME_URL: ${{ secrets.RESUME_URL }}
          CONTACT_FORM_URL: ${{ secrets.CONTACT_FORM_URL }}
        run: |
          echo "resume_url: $RESUME_URL" >> src/_config.yml
          echo "contact_form_url: $CONTACT_FORM_URL" >> src/_config.yml
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./src
          destination: ./_site
          verbose: true
      - name: Inspect Output
        run: |
          echo "Inspecting the output of the Jekyll build..."
          cat src/_config.yml
          echo "Current directory:"
          ls
          echo "List of files in the _site directory:"
          ls _site/
          echo "Contents of the _site/index.html file:"
          cat _site/index.html
